### ISSUE TITLE
Compression of custom headers

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/nghttp3#100]
Our product makes extensive use of custom headers. nghttp3 seems to only compress a set of well known headers, but not custom headers. We suspect that sending these headers using their literal representation hurts performance and user experience, especially in slow networks. Another library we're using allows the user to specify which custom headers should be compressed. Would it be possible to provide a similar capability to nghttp3?

**Comment by tatsuhiro-t** [comment]
Compressing every header fields is not nice because it quickly fills up storage, especially there are large ones.
But compressing selected header fields by application would be a good workaround.
Perhaps, we can add new NGHTTP3_NV_FLAG to give a hint to the compressor.

**Comment by crytaljin** [comment]
@tatsuhiro-t Great idea! Do you have an estimate of when you'll be able to implement this?

**Comment by tatsuhiro-t** [comment]
#100 implements this.

**Comment by crytaljin** [comment]
Thank you!!

**Comment by amirlivneh** [comment]
I can confirm that this change reduces the latency of HTTP requests, especially on cellular networks at the high percentiles of latency distribution. This translates to a measurable improvement in user experience.
