### ISSUE TITLE
NGHTTP3_NV_FLAG_NEVER_INDEX behavior

### ISSUE THREAD

**Issue by crytaljin** [ngtcp2/nghttp3#103]
Is it expected behavior that if we set flag NGHTTP3_NV_FLAG_NEVER_INDEX for a header that is usually statically indexed, it will still be indexed with nghttp3_qpack_encoder_write_static_indexed_name()? I see it hitting [that line](https://github.com/ngtcp2/nghttp3/blob/main/lib/nghttp3_qpack.c#L1541) regardless of the header value, so content-length = 0 for example would still be indexed as literal field line with static name reference.

**Comment by tatsuhiro-t** [comment]
nghttp3_qpack_encoder_write_static_indexed_name does not index field value.  It just uses static name from static table.  Field value is still encoded in literal string.  never-index still allows an encoder to use name from tables.  It just prevents an encoder from indexing field value by adding it to the dynamic table.

**Comment by crytaljin** [comment]
Ahh ok that makes sense, thanks!
