### ISSUE TITLE
Enforcing const-qualified for fields in `nghttp3_nv` seems to cause inconvenience

### ISSUE THREAD

**Issue by zguo-code** [ngtcp2/nghttp3#142]
We found a bit inconvenient to use the [`nghttp3_conn_submit_request`](https://github.com/ngtcp2/nghttp3/blob/edd29958595376d236e9244658de6da232c97dfd/lib/includes/nghttp3/nghttp3.h#L2466) API after https://github.com/ngtcp2/nghttp3/pull/130 is merged.

The inconvenience is due to the fact that we now had to do additional casting in our code like below (unless the pointers are also saved in another variable or freed automatically):

Before https://github.com/ngtcp2/nghttp3/pull/130:
```c
free(headers[i].name);
free(headers[i].value);
```
After https://github.com/ngtcp2/nghttp3/pull/130:
```c
free((uint8_t*)headers[i].name);
free((uint8_t*)headers[i].value);
``` 

Can we consider only retaining the const qualifier for `nghttp3_nv` as a parameter of `nghttp3_conn_submit_request` API, but not retaining the const qualifiers for the `name` and `value` fields of the [`nghttp3_nv`](https://github.com/ngtcp2/nghttp3/blob/0698efce4c7d54503849cbc6e29ef4cdcb9f236b/lib/includes/nghttp3/nghttp3.h#L747) struct please? Thanks.

CC: @amirlivneh

**Comment by tatsuhiro-t** [comment]
Note that we are approaching RC releases followed by v1 release.  After v1, this kind of change wont happen.

**Comment by zguo-code** [comment]
Thanks @tatsuhiro-t for your reply. We couldn't think of a strong reason for rolling back the change, so I'm closing the issue now.

CC: @amirlivneh
