### ISSUE TITLE
cmake error on CMAKE_C_BYTE_ORDER

### ISSUE THREAD

**Issue by Keitagit-kun** [ngtcp2/nghttp3#145]
nghttp3 VERSION 0.12.0 configuration with cmake up to 3.12.4 fails  on
```
if(${CMAKE_C_BYTE_ORDER} STREQUAL "BIG_ENDIAN")
  set(WORDS_BIGENDIAN 1)
endif()
```
while advertised cmake_minimum_required(VERSION 3.1)
maybe WORDS_BIGENDIAN should be  some other way to respect advertised cmake version? Or turned to actual visible/manual option and not automatic one?
I'm deleting it for now - shoud it not pose any probllems on windows? (works OK - windows - little endian)

**Comment by tatsuhiro-t** [comment]
I will change minimum cmake version which has CMAKE_C_BYTE_ORDER.
If you use little endian machine, then yes, you can delete it and it should work.
