### ISSUE TITLE
Windows DLL missing version information and other file properties

### ISSUE THREAD

**Issue by geraldcombs** [ngtcp2/nghttp3#182]
The nghttp2 sources have a resource file that sets the ProductName, ProductVersion, and other properties: https://github.com/nghttp2/nghttp2/blob/master/lib/version.rc.in. A corresponding file appears to be missing in this repository, and generated DLLs don't have those properties set. Would it be possible to add this?

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  If anyone is interested in it. please send a pull request to add the file.
