### ISSUE TITLE
1.2.0 build error: `fatal error: sfparse/sfparse.h: No such file or directory`

### ISSUE THREAD

**Issue by barracuda156** [ngtcp2/nghttp3#203]
```
nghttp3_http.c:35:10: fatal error: sfparse/sfparse.h: No such file or directory
   35 | #include "sfparse/sfparse.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [nghttp3_http.lo] Error 1
```

**Comment by barracuda156** [comment]
> Which source are you building from: git, or github zip archive, or a tar ball?

@tatsuhiro-t Tarball from GH archive: https://github.com/macports/macports-ports/blob/0a8f14ef232d5a968b000e61ee3f56f7dd41c14a/net/nghttp3/Portfile#L6-L17
(I tried to update it locally to 1.2.0 to update the port, just changing the version, the source remained the same.)

**Comment by ms178** [comment]
I can confirm the issue (seen with GCC 13.2.1 and Clang-19-git), I also see this build failure with 1.2.0. I am using the following PKGBUILD on Arch:

```
# Maintainer: kpcyrd <kpcyrd[at]archlinux[dot]org>

pkgname=libnghttp3
pkgver=1.2.0
pkgrel=2.1
pkgdesc="HTTP/3 library written in C"
url='https://github.com/ngtcp2/nghttp3'
arch=('x86_64')
license=('MIT')
provides=('libnghttp3.so')
source=("${pkgname}-${pkgver}.tar.gz::https://github.com/ngtcp2/nghttp3/archive/refs/tags/v${pkgver}.tar.gz")
sha256sums=('b3ffb23a90442a0eafe8bfbefbc8b4ffb5179d68a7c0b8a416a34cf04b28d7c5')

prepare() {
  cd nghttp3-${pkgver}
  autoreconf -vfi
}

build() {
  cd nghttp3-${pkgver}
  ./configure \
    --prefix=/usr
  make
}

check() {
  cd nghttp3-${pkgver}
  make check
}

package() {
  cd nghttp3-${pkgver}/lib
  make DESTDIR="${pkgdir}" install
  install -Dm644 ../COPYING -t "${pkgdir}/usr/share/licenses/${pkgname}"
}

# vim: ts=2 sw=2 et:

```

**Comment by tatsuhiro-t** [comment]
The archives that generated by github automatically do not work now because it does not contain files pulled from git submodule.
Please consider to download a tar archive with the prefix `nghttp3-` (e.g., nghttp3-1.2.0.tar.xz)

**Comment by barracuda156** [comment]
@tatsuhiro-t Yes, that worked, thank you.
