### ISSUE TITLE
About Encoder and Decoder Streams

### ISSUE THREAD

**Issue by bufan22** [ngtcp2/nghttp3#215]
According to RFC 9204 4.2
`HTTP/3 endpoints contain a QPACK encoder and decoder. Each endpoint MUST initiate, **at most**, one encoder stream and, at most, one decoder stream`

But according to [Online documentation](https://nghttp2.org/nghttp3/)
`HTTP/3 requires **at least** 3 local unidirectional streams for a control stream and QPACK encoder/decoder streams.`

Is there a conflict with the RFC?

**Comment by tatsuhiro-t** [comment]
No.  Read https://datatracker.ietf.org/doc/html/rfc9114#section-6.2.1
