### ISSUE TITLE
Compressed response header size

### ISSUE THREAD

**Issue by nishantnori** [ngtcp2/nghttp3#219]
nghttp3 currently provides `recv_header` callback that returns HTTP response header name and HTTP response header value. But this is called after the QPACK decompression. Is there a way to get the size of the compressed response headers from nghttp3?

**Comment by tatsuhiro-t** [comment]
nghttp3_conn_get_frame_payload_left called inside nghttp3_begin_headers returns the size of HEADERS frame which contains compressed header fields.
