### ISSUE TITLE
acked_data() callback for requests without body?

### ISSUE THREAD

**Issue by hyunjic** [ngtcp2/nghttp3#226]
hi, we want to record the time when request last byte is acked. Current implementation seems to only call acked_data() callback when data type is alien, i.e. when request has a body. Is there a way to know when header (data type: private) is acked for e.g. GET requests to consistently mark the end of request? Or can we add another callback? Thanks.

**Comment by tatsuhiro-t** [comment]
There is no way to know when request header is acknowledged, and no plan to add such callback.
