### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by bmarques1995** [ngtcp2/nghttp3#239]
My dears, do u have a sample repository of a HTTP server with the lib? I'm with difficulties to understand the docs and the usage cases, and another example could be useful

**Comment by tatsuhiro-t** [comment]
See https://github.com/ngtcp2/ngtcp2/tree/main/examples/server.cc

**Comment by bmarques1995** [comment]
> See https://github.com/ngtcp2/ngtcp2/tree/main/examples/server.cc

By the way, can u verify there my pull request? The same of the #228

**Comment by Andersama** [comment]
I was digging for an example, maybe it'd be worth referencing that example in a README underneath the examples directory? It's a bit convoluted to look for an example of this library inside another repo. Would not have spotted it if I'd not bothered to check the issues tab.
