### ISSUE TITLE
nghttp3_conn_read_stream return -607 when received settings from chrome.

### ISSUE THREAD

**Issue by jfclere** [ngtcp2/nghttp3#240]
I have received (log from openssl sqlog file) from a chrome client:
{"name":"transport:parameters_set","data":{"owner":"remote","original_source_connection_id":"a2efe8e367545ba3","initial_max_data":15728640,"initial_max_stream_data_bidi_local":6291456,"initial_max_stream_data_bidi_remote":6291456,"initial_max_stream_data_uni":6291456,"initial_max_streams_bidi":100,"initial_max_streams_uni":103,"max_udp_payload_size":1472,"max_idle_timeout":30000,"disable_active_migration":false},"time":0}
if I ignore the error the server will send:
{"name":"transport:parameters_set","data":{"owner":"local","disable_active_migration":true,"original_destination_connection_id":"a2efe8e367545ba3","initial_source_connection_id":"4214a09e2bd71dcf","max_idle_timeout":30000,"max_udp_payload_size":1200,"active_connection_id_limit":2,"max_ack_delay":25,"initial_max_data":786432,"initial_max_stream_data_bidi_local":524288,"initial_max_stream_data_bidi_remote":524288,"initial_max_stream_data_uni":524288,"initial_max_streams_bidi":100,"initial_max_streams_uni":100},"time":0}

I can't figure why -607 is returned I am using nghttp3_settings_default() in the server before calling nghttp3_conn_server_new()

**Comment by tatsuhiro-t** [comment]
nghttp3_conn_read_stream returns -607 if:
- it receives PRIORITY_UPDATE frame which references Stream ID which is not client initiated stream or Stream ID exceeds what server allows; or
- it receives PRIORITY_UPDATE frame which references Push ID; or
- it receives GOAWAY frame that contains increasing Stream ID.
