### ISSUE TITLE
NGHTTP3_ERR_TEMPORAL_CALLBACK_FAILURE

### ISSUE THREAD

**Issue by doublex** [ngtcp2/nghttp3#257]
`NGHTTP3_ERR_TEMPORAL_CALLBACK_FAILURE` would be quite useful, but is marked as `TODO` in the docs:
https://nghttp2.org/nghttp3/types.html#c.nghttp3_read_data_callback

Is it valid to call `ngtcp2_conn_shutdown_stream(NGHTTP3_H3_REQUEST_CANCELLED)` within the data-reader callback?
If so, what is the callback supposed to return? `NGHTTP3_ERR_WOULDBLOCK`?

**Comment by tatsuhiro-t** [comment]
It is ok to call ngtcp2_conn_shutdown_stream within the callback.  NGHTTP3_ERR_WOULDBLOCK should work.

**Comment by doublex** [comment]
@tatsuhiro-t 
Thank you for all these great services.

**Comment by doublex** [comment]
Maybe it would be worth adding a note to the documentation?

**Comment by tatsuhiro-t** [comment]
It is rather odd to mention ngtcp2 API in nghttp3 API documentation.
The error code currently permitted is NGHTTP3_ERR_WOULDBLOCK or NGHTTP3_ERR_CALLBACK_FAILURE.  The latter shutdown the connection, so the choice is rather obvious, but if you have an idea to improve the doc, would you mind make a PR?

**Comment by doublex** [comment]
You are right.
Sorry for the inconvenience.
