### ISSUE TITLE
Regarding performing Huffman encoding always

### ISSUE THREAD

**Issue by nishantnori** [ngtcp2/nghttp3#279]
This is regarding 8fd4bd833e764f5b0d46f7b8ed2ae2708cafbfd1 (Do huffman encoding only when the reduction is more than 25%). 

We ran an experiment on the client-side comparing performing Huffman encoding always (control group) vs. performing Huffman encoding only when the reduction is > 25% (test group). We found that the control group generally performs better for the client, likely due to sending more data on wire in the test group. 

Do you think it is better to perform Huffman encoding always as default?

**Comment by tatsuhiro-t** [comment]
There is a trade off in huffman encoding between transfer size reduction and decoding overhead.
It actually massively impact server side CPU usage when header field set is large, which is quite common these days.
If 25% might be too large, it can be lowered to find the sweet spot.
BTW, what is the metrics you use when comparing those groups?

**Comment by tatsuhiro-t** [comment]
I decided to revert the change because:
1. This is encoder change that decoder cannot enforce, that makes this strategy ineffective.
2. One can workaround this by storing fields in dynamic table.

**Comment by tatsuhiro-t** [comment]
#280

**Comment by nishantnori** [comment]
Thanks. We use nghttp3 on the client-side app and we noticed that with conditional Huffman encoding, the app generally takes longer to start loading content.
