### ISSUE TITLE
Assertion in conn_decode_headers() may fail after receiving a valid header block

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/nghttp3#28]
After `nghttp3_conn_read_bidi()` calls `nghttp3_conn_on_headers()`, the stream may be blocked. If the header block that blocked the stream didn't have representations, `rstate->left` would be 0. If `conn_decode_headers()` is later called on the stream via `conn_process_blocked_stream_data()`, `srclen` will be to 0 and this assertion will fail:
https://github.com/ngtcp2/nghttp3/blob/5047fbb682a6c3d3300482886f0e35e9141cfcfd/lib/nghttp3_conn.c#L2119

**Comment by tatsuhiro-t** [comment]
Thank you for telling this bug.  I think this assertion should be deleted.  I'll add test case to verify that.

**Comment by tatsuhiro-t** [comment]
37017cee122f54e24d9519e6b867c78c5bbcee0d has a fix and test case.

**Comment by amirlivneh** [comment]
Thanks!
