### ISSUE TITLE
Are we have Rust bindings?

### ISSUE THREAD

**Issue by taikulawo** [ngtcp2/nghttp3#281]
We are developing a Rust based gateway, which need HTTP3 support.

We are finding a pure HTTP3 library which don't rely on any special QUIC transport implemention. nghttp3 is good for our demand 
but no Rust bindings from I know. 

I can help if there are next plan.

**Comment by tatsuhiro-t** [comment]
At the moment, we do not have particular plan for it.  I do not know it can be generated by a tool or needs manual editing, but I think it does not need to be in this repo, so you can experiment it with your own to see how it looks like.

**Comment by taikulawo** [comment]
thanks

**Comment by taikulawo** [comment]
I have done this, will release news when it's ready

**Comment by taikulawo** [comment]
@tatsuhiro-t Hi, I have open sourced rust `nghttp3` binding https://github.com/taikulawo/nghttp3. :)

It works in our prod env
