### ISSUE TITLE
qpack value length prefix error after reading a literal name

### ISSUE THREAD

**Issue by Kulsk** [ngtcp2/nghttp3#30]
In the case of Encoder Instruction _Insert Without Name Reference_ (https://tools.ietf.org/html/draft-ietf-quic-qpack-16#section-4.3.3), use s2load to perform a QUIC request, and if the returned Encoder Instructions from server contain a "Insert Without Name Reference", the code might return ERR_QPACK_ENCODER_STREAM_ERROR problems if value length is >= 31 bytes.
This would print: 
nghttp3_conn_read_stream: ERR_QPACK_ENCODER_STREAM_ERROR

In this instruction, the prefix of Name Length is 5. after reading the Name Length and Name String, it comes the Value Length field, with a prefix of 7.
        0   1   2   3   4   5   6   7
      +---+---+---+---+---+---+---+---+
      | 0 | 1 | H | Name Length (5+)  |
      +---+---+---+-------------------+
      |  Name String (Length bytes)   |
      +---+---------------------------+
      | H |     Value Length (7+)     |
      +---+---------------------------+
      |  Value String (Length bytes)  |
      +-------------------------------+

More specifically, in the  function nghttp3_qpack_decoder_read_encoder, the prefix is restored in the decoder->rstate.prefix. when reading Name Length, this variable is set to 5, and after the NGHTTP3_QPACK_ES_STATE_READ_NAME code section (nghttp3_qpack.c, line 2946), it remains to be 5, but should be set to 7. And if the Value Length is between [31, 127) , that is [2^5-1, 2^7-1), the reading of vaint will be error, and get an error Value Length, and cause the huffman check of Value to be error.

I try to change the prefix to 7 at the end of NGHTTP3_QPACK_ES_STATE_READ_NAME case, turned out to be work well

**Comment by tatsuhiro-t** [comment]
Thank you for finding this bug.  Fix committed via d9a6eae
