### ISSUE TITLE
Support for HTTP/3 PRIORITY_UPDATE frame

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/nghttp3#36]
Our experiments show benefits from using HTTP/3 PRIORITY_UPDATE frames over just the Priority header. We're interested in having client-side support for the frame in nghttp3.

**Comment by tatsuhiro-t** [comment]
Will do.  Is the experimental result publicly available?  I'm interested in the situation where reprioritization helps web performance.

**Comment by amirlivneh** [comment]
Thank you @tatsuhiro-t. The experiment results are not publicly available yet. One of my colleagues is working on summarizing them. Note that the experiment didn't involve a web browser, as you mentioned you're specifically interested in web performance.

**Comment by tatsuhiro-t** [comment]
Thank you.  PRIORITY_UPDATE frame support has been added to main.

**Comment by amirlivneh** [comment]
Looks great. Thank you!
