### ISSUE TITLE
Support for nghttp3_conn_submit_headers() & nghttp3_conn_submit_data()

### ISSUE THREAD

**Issue by ksmurchison** [ngtcp2/nghttp3#37]
Are there any plans to support these functions which appear in nghttp2?
My application likes to send headers and one or more data chunks independently.
Can nghttp3_conn_submit_response() be called with zero headers to send just data?

**Comment by tatsuhiro-t** [comment]
You can submit header fields with nghttp3_conn_submit_response.  Then you can delay the transmission of response body by returning NGHTTP3_ERR_WOULDBLOCK from nghttp3_read_data_callback and call nghttp3_conn_resume_stream  when data is ready.  In HTTP/3 you cannot send response body without header fields, so the current API should satisfy your needs.

**Comment by ksmurchison** [comment]
I understand that a HTTP response has to have headers, but my reading of the spec says that a response is defined as the following series of frames:

HEADERS
(DATA)*
(HEADERS)?

This appears to be the same as HTTP/2.  nghttp2 allows me to submit the headers by calling nghttp2_conn_submit_headers() and then submitting one or more data chunks using calls to nghttp2_conn_submit_data()
