### ISSUE TITLE
C++ wrapper / boost integration

### ISSUE THREAD

**Issue by atari83** [ngtcp2/nghttp3#40]
Hello and thanks for all efforts on this project.
I was curious to know if nghttp3 would have C++ wrapper library ? just like what we have currently in nghttp2 ?
Could we expect to have this in nghttp3 roadmap ?

Thanks,

**Comment by tatsuhiro-t** [comment]
I have no plan to add C++ wrapper library for the foreseeable future.

**Comment by atari83** [comment]
Thank you.
