### ISSUE TITLE
Should we use uint64_t everywhere for offset/size variables

### ISSUE THREAD

**Issue by JunqiWang** [ngtcp2/nghttp3#44]
stream ack_offset is uint64_t, however, unsent_bytes/unscheduled_bytes etc are size_t. Should we use uint64_t everywhere?
https://github.com/ngtcp2/nghttp3/blob/main/lib/nghttp3_stream.h#L212-L225

**Comment by tatsuhiro-t** [comment]
It might make 32bit system's life a bit easier.
Fix committed via 3fb66e34de5d282371eabcaba158e3a1b365cfa1
