### ISSUE TITLE
Have any plan to support H3 datagram?

### ISSUE THREAD

**Issue by xiaozhihong** [ngtcp2/nghttp3#46]
Hi, does nghttp3 have any plan to support the [H3 datagram draft](https://datatracker.ietf.org/doc/html/draft-ietf-masque-h3-datagram-05)?

**Comment by tatsuhiro-t** [comment]
I have not read the draft yet and do not know much about it, but once the draft is settled and matured, I definitely try to implement it.

**Comment by xiaozhihong** [comment]
> I have not read the draft yet and do not know much about it, but once the draft is settled and matured, I definitely try to implement it.

Thanks for your reply.

**Comment by hlevring** [comment]
Hi just wanted to see if there is any update on this?

**Comment by tatsuhiro-t** [comment]
No progress on this one.

**Comment by donovano** [comment]
Hi, I did not see further comments on this issue. Since this is a RFC now (https://datatracker.ietf.org/doc/html/rfc9297) are there plans to add it or are you possibly adding it already?

**Comment by tatsuhiro-t** [comment]
We have a plan but have not done anything about it.

**Comment by tatsuhiro-t** [comment]
#114 has been merged.  Now you can send and receive SETTINGS_H3_DATAGRAM.
QUIC stack which supports DATAGRAM most likely offers an API to send DATAGRAM (e.g., https://nghttp2.org/ngtcp2/ngtcp2_conn_writev_datagram.html).  You can use it directly, and encode stream id / 4 you want, and then data.

**Comment by donovano** [comment]
Great, I will try that, thanks
