### ISSUE TITLE
Should nghttp3_reset_stream() be implemented on client side?

### ISSUE THREAD

**Issue by crytaljin** [ngtcp2/nghttp3#76]
In the commit [Treat NGHTTP3_ERR_MALFORMED_HTTP_HEADER as stream error](https://github.com/ngtcp2/nghttp3/commit/9a88ada163ab7012499662f2f80392d583d107ea), an HTTP header error is handled by [`conn_call_reset_stream()`](https://github.com/ngtcp2/nghttp3/commit/9a88ada163ab7012499662f2f80392d583d107ea#diff-892f38ef71a6d79fd33200bf216ca28e6a66b6d4287bae4ead6f8dd824b8a80eR1443), which calls the [`reset_stream`](https://github.com/ngtcp2/nghttp3/blob/9a88ada163ab7012499662f2f80392d583d107ea/lib/nghttp3_conn.c#L164) callback. The documentation for the callback says that it should only be implemented on [server side](https://github.com/ngtcp2/nghttp3/blob/41a06689483cf9f54403e72946c903052bc416ec/lib/includes/nghttp3/nghttp3.h#L1882), so I'm wondering what the client side behavior should be in the case of a malformed HTTP header.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  With the recent change, client also should implement reset_stream callback.  Will fix the documentation.

**Comment by crytaljin** [comment]
Thanks!
