### ISSUE TITLE
Setting priority for each URI

### ISSUE THREAD

**Issue by nEghbal** [ngtcp2/nghttp3#78]
Hello,

How I can set urgency and incremental values for each URI at client side (ngtcp2 examples/client)? 
I realized that in ngtcp2/examples/server.cc these values will be set if (1 << UF_QUERY), but I am not sure how I can add query as part of the request.

I have added priority in client_base.h as follows:
struct Request {
  std::string_view scheme;
  std::string authority;
  std::string path;
  **std::string priority;**
};

And I have changed submit_http_request in client.cc as follows:
std::array<nghttp3_nv, 7> nva{
      util::make_nv(":method", config.http_method),
      util::make_nv(":scheme", req.scheme),
      util::make_nv(":authority", req.authority),
      util::make_nv(":path", req.path),
      util::make_nv("user-agent", "nghttp3/ngtcp2 client"),
      **util::make_nv("priority", req.priority),**
  };

Thanks in advance.

**Comment by tatsuhiro-t** [comment]
Query is a part of path in ngtcp2 client.  If you give, for instance, `https://127.0.0.1/path?u=1`, `/path?u=1` is included in req.path.

**Comment by nEghbal** [comment]
Oh, I see.
So I do not need to add those two lines.

**Comment by tatsuhiro-t** [comment]
If you use the special ability of ngtcp2 server, yes.
