### ISSUE TITLE
nghttp3_conn_shutdown() behavior

### ISSUE THREAD

**Issue by crytaljin** [ngtcp2/nghttp3#86]
Hello, the [description](https://github.com/ngtcp2/nghttp3/blob/main/lib/includes/nghttp3/nghttp3.h#L2358-L2360) for `nghttp3_conn_shutdown` says
```
 * `nghttp3_conn_shutdown` starts graceful shutdown.  It should be
 * called after `nghttp3_conn_submit_shutdown_notice` and a couple of
 * RTT. 
```
but the [unit tests](https://github.com/ngtcp2/nghttp3/blob/main/tests/nghttp3_conn_test.c#L2786) don't call `nghttp3_conn_submit_shutdown_notice`. What should be the correct behavior here?

**Comment by tatsuhiro-t** [comment]
If you need "graceful shutdown", nghttp3_conn_submit_shutdown_notice is needed.
Otherwise, just nghttp3_conn_shutdown would do normal shutdown which might reject some in-flight requests.

**Comment by crytaljin** [comment]
Thanks for the response! Could you clarify in what situation some in flight requests might be rejected? In my understanding a GOAWAY will be sent and all new requests will be rejected, but existing requests will finish before connection is closed.

**Comment by tatsuhiro-t** [comment]
https://www.rfc-editor.org/rfc/rfc9114.html#section-5.2

> An endpoint that is attempting to gracefully shut down a connection can send a [GOAWAY](https://www.rfc-editor.org/rfc/rfc9114.html#frame-goaway) frame with a value set to the maximum possible value (262-4 for servers, 262-1 for clients). This ensures that the peer stops creating new requests or pushes. After allowing time for any in-flight requests or pushes to arrive, the endpoint can send another [GOAWAY](https://www.rfc-editor.org/rfc/rfc9114.html#frame-goaway) frame indicating which requests or pushes it might accept before the end of the connection. This ensures that a connection can be cleanly shut down without losing requests.

nghttp3_conn_submit_shutdown_notice does exactly the first GOAWAY described above.

**Comment by crytaljin** [comment]
That makes sense, thanks!
